export const passengerType = {
    'airline_Arrival': '',
    'airline_Departure': '',
    'booking_Date': null,
    'booking_Id': '',
    'car_Name_Arrival': null,
    'car_Name_Departure': null,
    'car_Transfer_Type_Arrival': null,
    'car_Transfer_Type_Departure': null,
    'check_By_Lc': false,
    'check_By_Rep': false,
    'contact_Number': null,
    'datetime_Arrival': '',
    'datetime_Departure': '',
    'passenger_Type': null,
    'flightNo_Arrival': null,
    'flightNo_Departure': null,
    'going_To': null,
    'id': null,
    'leaving_From': null,
    'number_Of_Pax': null,
    'number_Of_Rooms': null,
    'pax_Name': '',
    'room_Number': null,
    'room_Type': '',
    'supplier_Arrival': null,
    'supplier_Departure': null,
    'supplier_Reference': '',
    'terminal_Arrival': null,
    'terminal_Departure': null,
    'hotel_Name': '',
    'pickup_Time': null,
    'remarks_Field': '',
    'hotel_Id': null,
    'lC_First_Name': '',
    'lC_Last_Name': ''
};

export class PassengerType {
    airline_Arrival: string;
    airline_Departure: string;
    booking_Date: null;
    booking_Id: string;
    car_Name_Arrival: null;
    car_Name_Departure: null;
    car_Transfer_Type_Arrival: null;
    car_Transfer_Type_Departure: null;
    check_By_Lc: boolean;
    check_By_Rep: boolean;
    contact_Number: null;
    datetime_Arrival: string;
    datetime_Departure: string;
    passenger_Type: null;
    flightNo_Arrival: null;
    flightNo_Departure: null;
    going_To: null;
    id: null;
    leaving_From: null;
    number_Of_Pax: null;
    number_Of_Rooms: null;
    pax_Name: string;
    room_Number: null;
    room_Type: string;
    supplier_Arrival: null;
    supplier_Departure: null;
    supplier_Reference: string;
    terminal_Arrival: null;
    terminal_Departure: null;
    hotel_Name: string;
    hotel_Id: null;
    pickup_Time: Date;
    remarks_Field: string;
    lC_First_Name: string;
    lC_Last_Name: string;
}
