export const hotels = [
    {
        'Hotel': 'FLORA GRAND HOTEL',
        'LC': 'AKBAR ABBASIAN',
    },
    {
        'Hotel': 'ASTERION PALACE',
        'LC': 'SIAMAK SABER',
    },
    {
        'Hotel': 'NASSIMA ROYAL HOTEL',
        'LC': 'TAHEREH HAKIMELAHI',
    },
    {
        'Hotel': 'Burj Al Arab',
        'LC': 'ALISALEH GHAHESTANI',
    },
    {
        'Hotel': 'IBERIA',
        'LC': 'SEYEDALOLAMA SEYEDMOHAMMADAMIN',
    },
    {
        'Hotel': 'PRIME HOTEL',
        'LC': 'ALIREZA GANJIDELSHAD',
    },
    {
        'Hotel': 'RAMADA ENCORE',
        'LC': 'REZA SHABANGHAMSARI',
    },
    {
        'Hotel': 'AMBASADORI HISTORICAL PART',
        'LC': 'IMAN ABRISHAMI',
    },
    {
        'Hotel': 'GRAND HOTEL',
        'LC': 'MOJTABA MOHAMMAGHALEH',
    },
    {
        'Hotel': 'CONTINENT CRON PALACE TBILISI HOTEL',
        'LC': 'ROJA AZAD',
    },
    {
        'Hotel': 'NIKKI BEACH RESORT',
        'LC': 'FATEMEH SALAHINEZHAD',
    },
    {
        'Hotel': 'SWISSOTEL AL GHURAIR',
        'LC': 'SEYEDMOJTABA SALIMBAHRAMI',
    },
    {
        'Hotel': 'SUN & SANDS SEA VIEW HOTEL',
        'LC': 'LEILA HASEMI',
    },
    {
        'Hotel': 'AVENUE HOTEL DUBAI',
        'LC': 'AMIRREZA GOLESTANI',
    },
    {
        'Hotel': 'NOVOTEL WORLD TRADE CENTRE',
        'LC': 'FERESHTEH MOMAYEZHAGHIGHI',
    },
    {
        'Hotel': 'GRAND HYATT DUBAI',
        'LC': 'MAJID RAHMANI',
    },
    {
        'Hotel': 'IBIS AL BARSHA',
        'LC': 'MASOOMEH ZARGAR',
    },
    {
        'Hotel': 'RIXOS BAB AL BAHR',
        'LC': 'HASAN SAHRAEIAFSHAR',
    },
    {
        'Hotel': 'ROYAL CONTINENTAL HOTEL',
        'LC': 'MATIN SHAMLOONIA',
    },
    {
        'Hotel': 'CROWNE PLAZA SHEIKH ZAYED',
        'LC': 'SARA KHADEMIAN',
    },
    {
        'Hotel': 'Royal Falcon',
        'LC': 'BEHROOZ BAGHERI',
    },
    {
        'Hotel': 'DORUS HOTEL',
        'LC': 'MOHAMMAD KHAVAND',
    },
    {
        'Hotel': 'Delmon Palace Hotel',
        'LC': 'MOHAMMAD TEIMOURIJERVEKANI',
    }
    // ,

    // 'FLORA GRAND HOTEL',
    // 'ASTERION PALACE',
    // 'NASSIMA ROYAL HOTEL',
    // 'Burj Al Arab',
    // 'IBERIA',
    // 'PRIME HOTEL',
    // 'RAMADA ENCORE',
    // 'AMBASADORI HISTORICAL PART',
    // 'GRAND HOTEL',
    // 'CONTINENT CRON PALACE TBILISI HOTEL',
    // 'TBILISI CENTRALI',
    // 'NIKKI BEACH RESORT',
    // 'SWISSOTEL AL GHURAIR',
    // 'SUN & SANDS SEA VIEW HOTEL',
    // 'AVENUE HOTEL DUBAI',
    // 'NOVOTEL WORLD TRADE CENTRE',
    // 'GRAND HYATT DUBAI',
    // 'IBIS AL BARSHA',
    // 'RIXOS BAB AL BAHR',
    // 'ROYAL CONTINENTAL HOTEL',
    // 'CROWNE PLAZA SHEIKH ZAYED',
    // 'Royal Falcon',
    // 'DORUS HOTEL',
    // 'Delmon Palace Hotel'
];

export const pax = [
    'FATEMEH SALAHINEZHAD',
    'SEYEDMOJTABA SALIMBAHRAMI',
    'RAHA KHOSRAVI',
    'LEILA HASEMI',
    'ALI KARIMI',
    'AMIRREZA GOLESTANI',
    'FERESHTEH MOMAYEZHAGHIGHI',
    'JAVAD ABTAEIKHEIRABADI',
    'MAJID RAHMANI',
    'MASOOMEH ZARGAR',
    'HASAN SAHRAEIAFSHAR',
    'MATIN SHAMLOONIA',
    'SARA KHADEMIAN',
    'BEHROOZ BAGHERI',
    'MOHAMMAD KHAVAND',
    'HOUMAN ASADPOURSHESHBAHREH',
    'MOHAMMAD TEIMOURIJERVEKANI',
    'HEDAYATOLLAH SHARAFI',
    'SOHAIL FARJAMI',
    'SHAHIN SHAMLOUREZAEI',
    'AKBAR ABBASIAN',
    'POORYA SAEIDIFARID',
    'SIAMAK SABER',
    'TAHEREH HAKIMELAHI',
    'ALISALEH GHAHESTANI',
    'SEYEDALOLAMA SEYEDMOHAMMADAMIN',
    'ALIREZA GANJIDELSHAD',
    'ALIREZA NOORI',
    'DANIAL SHIRINKAR',
    'MEYSAM ALAVINEJAD',
    'IMAN ABRISHAMI',
    'HOJAT KESHAVARZI',
    'MINA MOSTOFI',
    'ROJA AZAD',
    'HOSSEIN RASOLI',
    'LEILA NADREMANESH',
    'MOJTABA MOHAMMAGHALEH',
    'MOHAMMAD JAFARPOOR',
    'REZA SHABANGHAMSARI',
    'ABOLFAZL VAZIRIDOUZIN',
    'ESMAEIL HABIBI',
    'AYOUB DELJOUKHORTOUMI'
];
